{
 "title": "Go Process Details",
 "tags": [
  "Go",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "service_name",
    "label": "Service name",
    "query": "label_values(go_info{namespace=\"$namespace\",}, container)"
   },
   {
    "name": "pod_name",
    "label": "Pod name",
    "query": "label_values(go_info{namespace=\"$namespace\", container=\"$service_name\"}, pod)"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Go Process Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health: $pod_name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "repeat": "pod_name",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{exported_namespace=\"$namespace\", exported_pod=\"$pod_name\", exported_pod!~\".*deploy\", container=\"$service_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime: $pod_name",
   "type": "singlestat",
   "description": "Shows selected service uptime",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 1 },
   "repeat": "pod_name",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\", exported_pod!~\".*-deploy\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Goroutines: $pod_name",
   "type": "singlestat",
   "description": "Shows amount of goroutines active in the selected service",
   "gridPos": { "h": 3, "w": 6, "x": 13, "y": 1 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", pod=\"$pod_name\", container=\"$service_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Opened FD: $pod_name",
   "type": "singlestat",
   "description": "Shows amount of currently opened file descriptors",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "repeat": "pod_name",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\", pod=\"$pod_name\", container=\"$service_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Usage: $pod_name",
   "type": "graph",
   "description": "Summary of CPU usage by pod $pod_name.\n\nThe red line shows limit of CPUs usage for the process.\n\nThe values is indicated in Millicores. It is a special Kubernates metric means CPU core split into 1000 units.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "alias": "usage",
     "expr": "rate(container_cpu_usage_seconds_total{container=\"$service_name\", pod=\"$pod_name\", namespace=\"$namespace\"}[$inter])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "usage",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "limit",
     "expr": "kube_pod_container_resource_limits_cpu_cores{container=\"$service_name\", exported_pod=\"$pod_name\", exported_namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "limit",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    },
    {
     "alias": "request",
     "expr": "kube_pod_container_resource_requests_cpu_cores{container=\"$service_name\", exported_pod=\"$pod_name\", exported_namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "request",
     "measurement": "cpu/usage_rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "pod_container" },
      { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
      { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
     ]
    }
   ]
  },
  {
   "title": "Commited Memory $pod_name",
   "type": "graph",
   "description": "The amount of used memory",
   "gridPos": { "h": 7, "w": 11, "x": 10, "y": 4 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Heap",
     "expr": "kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\", exported_pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Limits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Heap",
     "expr": "kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$namespace\", container=\"$service_name\", exported_pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Non Heap : Code Cache",
     "expr": "container_memory_max_usage_bytes{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Non Heap : Code Cache",
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Heap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Non Heap : Code Cache",
     "expr": "go_memstats_mcache_sys_bytes{namespace=\"$namespace\", container=\"$service_name\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Non Heap",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open Files $pod_name",
   "type": "graph",
   "description": "The open file descriptor count",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 4 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "open",
     "expr": "process_open_fds{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Open",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory $pod_name",
   "type": "graph",
   "description": "Information about resident and virtual memory",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "repeat": "pod_name",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Resident Memory",
     "expr": "process_resident_memory_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Resident Memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Virtual Memory",
     "expr": "process_virtual_memory_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Virtual Memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC: Work time $pod_name",
     "type": "graph",
     "description": "Work time of garbage collector",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 20 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "s", "label": "pause/sec" }
     ],
     "targets": [
      {
       "alias": "Total GC Time",
       "expr": "rate(go_gc_duration_seconds_sum{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}[$inter])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Total GC Time",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC: Allocations",
     "type": "graph",
     "description": "Information about memory used for GC correct work",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Allocations",
       "expr": "go_memstats_next_gc_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Allocations",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "GC metadata",
       "expr": "go_memstats_gc_sys_bytes{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "GC metadata",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines $pod_name",
     "type": "graph",
     "description": "Shows information about goroutines and system threads amount",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Goroutines",
       "expr": "go_goroutines{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Goroutines",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "System Threads",
       "expr": "go_threads{container=\"$service_name\", namespace=\"$namespace\", pod=\"$pod_name\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "System Threads",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoint Statistics. Code: 2xx $pod_name",
     "type": "graph",
     "description": "Shows amount of successful requests to different URLs per second",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "expr": "rate(http_request_status{container=\"$service_name\", namespace=\"$namespace\", status=~\"2..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{path}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Endpoint Statistics. Code: 4xx $pod_name",
     "type": "graph",
     "description": "Shows amount of requests to different URLs per second with code 4xx",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "expr": "rate(http_request_status{container=\"$service_name\", namespace=\"$namespace\", status=~\"4..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{path}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP Endpoint Statistics. Code: 5xx $pod_name",
     "type": "graph",
     "description": "Shows amount of requests to different URLs per second with code 5xx",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "repeat": "pod_name",
     "yaxes": [
      { "format": "short", "label": "requests/sec" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "expr": "rate(http_request_status{container=\"$service_name\", namespace=\"$namespace\", status=~\"5..\", pod=\"$pod_name\"}[$inter]) OR on() vector(0)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{path}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}