ALTER TABLE deployment_versions ADD COLUMN IF NOT EXISTS createdWhen timestamp;
ALTER TABLE deployment_versions ADD COLUMN IF NOT EXISTS updatedWhen timestamp;
UPDATE deployment_versions SET createdWhen = CURRENT_TIMESTAMP,  updatedWhen = CURRENT_TIMESTAMP WHERE version = 'v1';

ALTER TABLE routes ADD COLUMN IF NOT EXISTS initialDeploymentVersion varchar(50) DEFAULT 'v1';
ALTER TABLE routes ADD COLUMN IF NOT EXISTS autoGenerated boolean NOT NULL DEFAULT false;