// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestEventBusClient is the client API for TestEventBus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestEventBusClient interface {
	Subscribe(ctx context.Context, in *Topic, opts ...grpc.CallOption) (TestEventBus_SubscribeClient, error)
	GetLastSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Event, error)
}

type testEventBusClient struct {
	cc grpc.ClientConnInterface
}

func NewTestEventBusClient(cc grpc.ClientConnInterface) TestEventBusClient {
	return &testEventBusClient{cc}
}

func (c *testEventBusClient) Subscribe(ctx context.Context, in *Topic, opts ...grpc.CallOption) (TestEventBus_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestEventBus_ServiceDesc.Streams[0], "/org.qubership.mesh.v3.test.bus.TestEventBus/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &testEventBusSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestEventBus_SubscribeClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type testEventBusSubscribeClient struct {
	grpc.ClientStream
}

func (x *testEventBusSubscribeClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *testEventBusClient) GetLastSnapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/org.qubership.mesh.v3.test.bus.TestEventBus/GetLastSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestEventBusServer is the server API for TestEventBus service.
// All implementations must embed UnimplementedTestEventBusServer
// for forward compatibility
type TestEventBusServer interface {
	Subscribe(*Topic, TestEventBus_SubscribeServer) error
	GetLastSnapshot(context.Context, *Empty) (*Event, error)
	mustEmbedUnimplementedTestEventBusServer()
}

// UnimplementedTestEventBusServer must be embedded to have forward compatible implementations.
type UnimplementedTestEventBusServer struct {
}

func (UnimplementedTestEventBusServer) Subscribe(*Topic, TestEventBus_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTestEventBusServer) GetLastSnapshot(context.Context, *Empty) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastSnapshot not implemented")
}
func (UnimplementedTestEventBusServer) mustEmbedUnimplementedTestEventBusServer() {}

// UnsafeTestEventBusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestEventBusServer will
// result in compilation errors.
type UnsafeTestEventBusServer interface {
	mustEmbedUnimplementedTestEventBusServer()
}

func RegisterTestEventBusServer(s grpc.ServiceRegistrar, srv TestEventBusServer) {
	s.RegisterService(&TestEventBus_ServiceDesc, srv)
}

func _TestEventBus_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Topic)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestEventBusServer).Subscribe(m, &testEventBusSubscribeServer{stream})
}

type TestEventBus_SubscribeServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type testEventBusSubscribeServer struct {
	grpc.ServerStream
}

func (x *testEventBusSubscribeServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _TestEventBus_GetLastSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestEventBusServer).GetLastSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/org.qubership.mesh.v3.test.bus.TestEventBus/GetLastSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestEventBusServer).GetLastSnapshot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TestEventBus_ServiceDesc is the grpc.ServiceDesc for TestEventBus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestEventBus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.qubership.mesh.v3.test.bus.TestEventBus",
	HandlerType: (*TestEventBusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastSnapshot",
			Handler:    _TestEventBus_GetLastSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TestEventBus_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "test_bus.proto",
}
